spring.application.name=ecommerce-backend
server.port=8080

spring.datasource.url=jdbc:h2:mem:ecommercedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origins=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173,https://localhost:3000,https://localhost:5173,https://127.0.0.1:3000,https://127.0.0.1:5173

app.keycloak.server-url=http://localhost:8081
app.keycloak.realm=ecommerce-realm
app.keycloak.client-id=ecommerce-client
app.keycloak.client-secret=lfPGxXt21IWL61VmVizO8QLILRPpXMw1
app.keycloak.admin-client-id=ecommerce-client
app.keycloak.admin-client-secret=lfPGxXt21IWL61VmVizO8QLILRPpXMw1

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/ecommerce-realm
